### ISSUE TITLE
After stopping webserver, it can't be restarted on very same port (until full unload of AppDomain) 

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/CompuMaster.Web.TinyWebServerAdvanced#2]
## Exception on restart
```
System.Net.HttpListenerException : Fehler beim Abhören von Präfix http://localhost:8033/, da es mit einer vorhandenen Registrierung auf dem Computer in Konflikt steht.
```

## Stacktrace
```
HttpListener.AddAllPrefixes()
HttpListener.Start()
WebServer.ListenerStart() Zeile 46
WebServer.ctor(Func`2 contentHandler, Func`2 responseHeadersHandler, String[] urls) Zeile 81
StartUpAndEnd.ReadFromHttpServerWithUtf8(Int32 port, Int32 headerContentTypeVariantToExecute, Int32 loopName) Zeile 21
```

**Comment by jochenwezel** [comment]
## ToDos

* [x] add unit test project
* [x] get this ticket fixed
* [x] add unit tests to CI/CD pipeline
